### ISSUE TITLE
Write Detox Tests

### ISSUE THREAD

**Issue by mattdeann** [yays-or-nays/yays-or-nays-FE#12]
- [x] About component
- [x] Categories component
- [x] HotTakes component

**Comment by LukeMason33** [comment]
Are we sure that we are able to write Cypress with react-native? This testing suite is recommended to do end-to-end tests on the react-native docs:
https://github.com/wix/Detox/blob/master/docs/Introduction.GettingStarted.md

**Comment by mattdeann** [comment]
> Are we sure that we are able to write Cypress with react-native? This testing suite is recommended to do end-to-end tests on the react-native docs:
> 
> https://github.com/wix/Detox/blob/master/docs/Introduction.GettingStarted.md

Title switched to Detox, thanks for looking up road! I don't see us hitting all of these anyways.
